name: Supotsu no Ochaya

services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure:3

  backend:
    image: ghcr.io/supotsu-no-ochaya/supotsu-backend:dev
    volumes:
      - ./pb_data:/app/pb_data
    restart: on-failure:3

  frontend:
    image: ghcr.io/supotsu-no-ochaya/frontend:main
    restart: on-failure:3
